import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStore } from '../store';
import { FileText, Download, Settings } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';

const REPORT_SECTIONS = [
  { id: 'context', label: 'System Context Model (Assets, Boundaries)' },
  { id: 'threats', label: 'Threat Register' },
  { id: 'cve', label: 'CVE Matching Audit' },
  { id: 'paths', label: 'Attack Path Analysis' },
  { id: 'risks', label: 'Risk Prioritization Scoring Math' },
  { id: 'mitigations', label: 'Mitigation & Action Plan' },
];

export function ReportsExport() {
  const { activeRunId } = useStore();
  const navigate = useNavigate();
  const [selectedSections, setSelectedSections] = useState<Set<string>>(
    new Set(REPORT_SECTIONS.map(s => s.id))
  );
  const [selectedFormat, setSelectedFormat] = useState<'PDF' | 'JSON' | 'MD'>('PDF');

  const toggleSection = (id: string) => {
    setSelectedSections(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  if (!activeRunId) {
    return (
      <div className="flex flex-col items-center justify-center h-[50vh] text-center">
        <div className="w-[72px] h-[72px] rounded-[20px] bg-info-bg flex items-center justify-center mb-[24px]">
          <FileText className="w-[36px] h-[36px] text-info-fg" />
        </div>
        <h2 className="text-[20px] font-bold text-text-primary mb-[8px]">No data to export</h2>
        <p className="text-[13px] text-text-secondary mb-[24px]">Complete the analysis pipeline before exporting.</p>
        <button className="btn-primary btn-md" onClick={() => navigate('/mitigations')}>
          Go to Mitigation Planner
        </button>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-[calc(100vh-140px)]">
      <header className="mb-[24px]">
        <h2 className="text-[20px] font-bold text-text-primary mb-[4px] tracking-tight">Reports & Export</h2>
        <p className="text-[13px] text-text-secondary">Configure and download security validation documentation generated by TARA for Run: {activeRunId}</p>
      </header>

      <div className="flex gap-[20px] min-h-[400px]">
        {/* Configurator */}
        <div className="w-[360px] card-panel h-max">
           <h3 className="text-[16px] font-bold text-text-primary border-b border-border-subtle pb-[12px] mb-[16px] flex items-center justify-between">
              Export Configuration
              <Settings className="w-[14px] h-[14px] text-text-muted"/>
           </h3>

           <div className="mb-[20px]">
             <h4 className="text-[12px] font-semibold text-text-muted uppercase tracking-wider mb-3">Include Sections</h4>
             <div className="space-y-[12px]">
               {REPORT_SECTIONS.map(section => (
                 <div key={section.id} className="flex items-center gap-[8px]">
                   <Checkbox
                     id={`section-${section.id}`}
                     checked={selectedSections.has(section.id)}
                     onCheckedChange={() => toggleSection(section.id)}
                     className="h-[16px] w-[16px] shrink-0 rounded-[4px] border-border-default data-[state=checked]:bg-accent-500 data-[state=checked]:border-accent-500"
                   />
                   <Label
                     htmlFor={`section-${section.id}`}
                     className="text-[13px] font-medium text-text-primary cursor-pointer leading-tight"
                   >
                     {section.label}
                   </Label>
                 </div>
               ))}
             </div>
           </div>

           <div className="pt-[20px] border-t border-border-subtle">
             <h4 className="text-[12px] font-semibold text-text-muted uppercase tracking-wider mb-3">Format</h4>
             <div className="grid grid-cols-3 gap-[8px] mb-[20px]">
               {(['PDF', 'JSON', 'MD'] as const).map(fmt => (
                 <button
                   key={fmt}
                   onClick={() => setSelectedFormat(fmt)}
                   className={`h-[36px] rounded-[8px] text-[13px] font-semibold transition-all ${
                     selectedFormat === fmt
                       ? 'border-2 border-accent-500 bg-accent-50 text-accent-700'
                       : 'border border-border-default hover:bg-surface-2 text-text-primary'
                   }`}
                 >
                   {fmt}
                 </button>
               ))}
             </div>

             <button className="btn-primary w-full h-[40px] text-[14px] flex items-center justify-center gap-[8px]">
                <Download className="w-[16px] h-[16px]" fill="currentColor" fillOpacity={0.2} /> Generate Output
             </button>
           </div>
        </div>

        {/* Preview Panel */}
        <div className="flex-1 bg-surface-1 border border-border-default rounded-[12px] p-[32px] overflow-hidden flex flex-col shadow-inner">
           <div className="flex-1 bg-white shadow-sm border border-border-subtle p-[40px] rounded-[4px] mx-auto w-full max-w-[700px] overflow-y-auto">
              <h1 className="text-[28px] font-bold text-text-primary mb-[8px]">TARA Security Baseline Report</h1>
              <p className="text-[13px] text-text-muted mb-[32px] border-b border-border-subtle pb-[20px]">Run ID: {activeRunId} • Generated: Just now</p>

              <div className="space-y-[24px]">
                 <div className="h-[20px] w-1/3 bg-[#f2f4f6] rounded"></div>
                 <div className="space-y-2">
                   <div className="h-[10px] w-full bg-[#f9fafb] rounded"></div>
                   <div className="h-[10px] w-[90%] bg-[#f9fafb] rounded"></div>
                   <div className="h-[10px] w-[95%] bg-[#f9fafb] rounded"></div>
                 </div>
                 <div className="h-[120px] w-full bg-[#f9fafb] border border-[#eceff2] rounded mt-4"></div>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
